In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
Temp_Sent=pd.read_csv('twitter.csv')
Temp_Sent

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/abdullahalshalan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


target          id                          date      flag  \
0             0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1             0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2             0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3             0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4             0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
1599995       4  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996       4  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997       4  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998       4  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599999       4  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                    user                                               text  
0        _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1          scotthamilton  is upset that he can't update his Facebook by ...  
2               mattycus  @Kenichan I dived many times for the ball. Man...  
3                ElleCTF    my whole body feels itchy and like its on fire   
4                 Karoli  @nationwideclass no, it's not behaving at all....  
...                  ...                                                ...  
1599995  AmandaMarie1028  Just woke up. Having no school is the best fee...  
1599996      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...  
1599997           bpbabe  Are you ready for your MoJo Makeover? Ask me f...  
1599998     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...  
1599999   RyanTrevMorris  happy #charitytuesday @theNSPCC @SparksCharity...  

[1600000 rows x 6 columns]

In [2]:
Temp_Sent = Temp_Sent.sample(frac = 1)
Temp_Sent

target          id                          date      flag  \
625959        0  2230422839  Thu Jun 18 17:05:29 PDT 2009  NO_QUERY   
1141408       4  1977172541  Sat May 30 20:17:11 PDT 2009  NO_QUERY   
1281012       4  2001693552  Tue Jun 02 01:44:56 PDT 2009  NO_QUERY   
1405920       4  2055272435  Sat Jun 06 09:01:01 PDT 2009  NO_QUERY   
1520552       4  2176210482  Mon Jun 15 03:14:01 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
881634        4  1685839880  Sun May 03 02:21:25 PDT 2009  NO_QUERY   
312906        0  2001628811  Tue Jun 02 01:31:24 PDT 2009  NO_QUERY   
1169509       4  1980265886  Sun May 31 06:13:47 PDT 2009  NO_QUERY   
168662        0  1962245059  Fri May 29 10:44:56 PDT 2009  NO_QUERY   
777460        0  2322426976  Wed Jun 24 22:35:50 PDT 2009  NO_QUERY   

                    user                                               text  
625959     BadMovieLover            I like my gym but theres nothing on tv   
1141408          kreeeem           decided to help my dad out with the car   
1281012        Cherye101  @PaulaAbdul your blogs on your site are so swe...  
1405920     tamchristine  @naystcb so, when are you going to pick up you...  
1520552          kkkarli  @hemisofia wow 6day school week? that's heavy!...  
...                  ...                                                ...  
881634          FadiPick  @mirkohumbert they are really cool icons. I du...  
312906          x3wennie  @melissaWOOF yeah . its several streets away ....  
1169509  IllusiveMcSorly  @derryo Love the Pontoon view the morning afte...  
168662      hunnybunnyco  Trying to figure out how to use Twitter..........  
777460              kg86  http://twitpic.com/8cn3p - @pradx in contrast ...  

[1600000 rows x 6 columns]

In [3]:
Sent = Temp_Sent[100000:200000]
Sent

target          id                          date      flag  \
566001        0  2206695961  Wed Jun 17 06:55:38 PDT 2009  NO_QUERY   
416740        0  2061372494  Sat Jun 06 20:43:54 PDT 2009  NO_QUERY   
1562672       4  2186883378  Mon Jun 15 19:28:32 PDT 2009  NO_QUERY   
949364        4  1823712580  Sat May 16 22:45:10 PDT 2009  NO_QUERY   
1368968       4  2050714467  Fri Jun 05 19:09:54 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
178557        0  1965998513  Fri May 29 16:56:06 PDT 2009  NO_QUERY   
1215834       4  1989582286  Mon Jun 01 02:04:01 PDT 2009  NO_QUERY   
203646        0  1972419686  Sat May 30 09:11:23 PDT 2009  NO_QUERY   
99320         0  1793585066  Thu May 14 03:15:17 PDT 2009  NO_QUERY   
1154887       4  1978961995  Sun May 31 01:05:34 PDT 2009  NO_QUERY   

                   user                                               text  
566001          martice  @zsbcreations annoying... they should turn off...  
416740          lydia20  @peterfacinelli I really hope I dont get disap...  
1562672         TheDahv  @rosemaryelaine By the way, you may consider t...  
949364         AimeeJ16  @ashlley I will and I will send my pics to Jon...  
1368968      jennsmalls  if pics are worth a thousand words, then it do...  
...                 ...                                                ...  
178557   hotchocolate05  I'm very upset right now, like I can't even fo...  
1215834         levi216  @ItsNeet Time will past by fast, I thnk, It di...  
203646        losimagic  @g0nk Thanks.  That's a shame   Hopefully they...  
99320    musicholic1997  @NileyLover09 watching a video of Demi's speec...  
1154887    caivillodres  is going to take some time this time. So it's ...  

[100000 rows x 6 columns]

In [5]:
def cleanText (text):    
    import re
    import string
    document = re.sub(r'\d+', '', text)
    document=document.lower()
    document = re.sub(r'[^\w\s]','',document)
    document=document.strip()
    stop_words = set(stopwords.words('english'))
    #tokinized_document= word_tokenize(document)
    #final = [i for i in tokinized_document if not i in stop_words]

    return document

In [6]:
document=''
stop = stopwords.words('english')
for index in Sent.index:
    document=cleanText(Sent.loc[index,'text']) 
    Sent.loc[index,'text']=document
Sent['text'] = Sent['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

Sent

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
<ipython-input-6-48d8522af30b>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Sent['text'] = Sent['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))


target          id                          date      flag  \
566001        0  2206695961  Wed Jun 17 06:55:38 PDT 2009  NO_QUERY   
416740        0  2061372494  Sat Jun 06 20:43:54 PDT 2009  NO_QUERY   
1562672       4  2186883378  Mon Jun 15 19:28:32 PDT 2009  NO_QUERY   
949364        4  1823712580  Sat May 16 22:45:10 PDT 2009  NO_QUERY   
1368968       4  2050714467  Fri Jun 05 19:09:54 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
178557        0  1965998513  Fri May 29 16:56:06 PDT 2009  NO_QUERY   
1215834       4  1989582286  Mon Jun 01 02:04:01 PDT 2009  NO_QUERY   
203646        0  1972419686  Sat May 30 09:11:23 PDT 2009  NO_QUERY   
99320         0  1793585066  Thu May 14 03:15:17 PDT 2009  NO_QUERY   
1154887       4  1978961995  Sun May 31 01:05:34 PDT 2009  NO_QUERY   

                   user                                               text  
566001          martice  zsbcreations annoying turn option searching ni...  
416740          lydia20   peterfacinelli really hope dont get disappointed  
1562672         TheDahv  rosemaryelaine way may consider invitation cha...  
949364         AimeeJ16  ashlley send pics jonasbrothersworldtourcomjon...  
1368968      jennsmalls  pics worth thousand words doesnt matter usuall...  
...                 ...                                                ...  
178557   hotchocolate05  im upset right like cant even formulate comple...  
1215834         levi216  itsneet time past fast thnk thnk youll b ready...  
203646        losimagic  gnk thanks thats shame hopefully theyll update...  
99320    musicholic1997  nileylover watching video demis speech girl di...  
1154887    caivillodres  going take time time one round experience im road  

[100000 rows x 6 columns]

In [7]:
X_Sent=Sent['text']
Y_Sent=Sent['target']

In [8]:
from sklearn import linear_model  
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_Sent, Y_Sent, test_size=0.25, random_state=1)

In [9]:
cv=CountVectorizer()
X_train_Vec1= cv.fit_transform(X_train)
X_train_Vec2= cv.transform(X_test)
a=X_train_Vec1.toarray()
#len(a[0])
a[0]

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
y_train=y_train.astype('int')

In [11]:
mnb.fit(X_train_Vec1,y_train)

MultinomialNB()

In [12]:
predcv=mnb.predict(X_train_Vec2)
predcv

array([4, 4, 0, ..., 4, 0, 4])

In [13]:
tfidf_Vec1=TfidfVectorizer(min_df=1, stop_words='english')
tfidfxc1=tfidf_Vec1.fit_transform (X_train)
tfidfxc2=tfidf_Vec1.transform (X_test)
a=tfidfxc1.toarray()
a[0]
tfidf_Vec1.inverse_transform(a[0])

[array(['isnt', 'oh', 'tent', 'waterproof', 'yeah'], dtype='<U110')]

In [14]:
mnb.fit(tfidfxc1,y_train)

MultinomialNB()

In [15]:
predtfidf=mnb.predict(tfidfxc2)
predtfidf

array([4, 4, 0, ..., 4, 0, 4])

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(predtfidf, predcv)
cm

array([[12851,   752],
       [  811, 10586]])